version: '3.8'

services:
    front-end:
        build:
            context: .
            dockerfile: Dockerfile
        # restart: always
        ports:
            - 3000:3000
#         networks:
#             - portfolio
# networks:
#     portfolio:
#         external: true
