import { Inter } from 'next/font/google';
import './globals.css';
import TanstackProvider from '@/shared/providers/TanstackProvider';
import Footer from '@/components/organisms/Footer';
import Header from '@/components/organisms/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TanstackProvider>
                    <Header />
                    <div>{children}</div>
                    <Footer />
                </TanstackProvider>
            </body>
        </html>
    );
}
